---
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: celery-action-worker
  namespace: hez
spec:
  pollingInterval: 5
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  maxReplicaCount: 50
  triggers:
  - type: rabbitmq
    metadata:
      mode: QueueLength
      value: "1"
      queueName: actions
      hostFromEnv: RABBITMQ_CONN
  jobTargetRef:
    parallelism: 1
    completions: 1
    template:
      spec:
        restartPolicy: Never
        containers:
        - name: worker
          image: dkci-worker:1.1
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef: { name: app-env }
          command:
          - celery
          - -A
          - worker_app.celery_app
          - worker
          - -Q
          - $(RABBITMQ_QUEUE)
          - -l
          - INFO
          - --concurrency=1
          - --max-tasks-per-child=1
          - --pool=solo
